name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: privilegedescalation/.github/.github/workflows/plugin-ci.yaml@main
